gitTestProject/src/objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Grand_Total__c</fullName>
        <formula>Total_Bill__c  +  Quote__r.Tax</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Grand Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Quote.OpportunityId</field>
                <operation>equals</operation>
                <valueField>$Source.Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Bill__c</fullName>
        <label>Total Bill</label>
        <summarizedField>Quote_Purchase__c.Total_Price__c</summarizedField>
        <summaryForeignKey>Quote_Purchase__c.Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gitTestProject/src/objects/Quote_Purchase__c.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Quote Line Item</relationshipLabel>
        <relationshipName>Quote_Purchase</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product1</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Purchase</relationshipLabel>
        <relationshipName>Quote_Purchase</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote1__c</fullName>
        <label>Quote1</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Purchase Order</relationshipLabel>
        <relationshipName>Quote_Purchase</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Price__c</fullName>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <formula>Subtotal__c   -   ( Subtotal__c  *  ( Discount__c  ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote Purchase</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Quote Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Purchase</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gitTestProject/src/classes/GeneratePdfController.cls
/* Controller of GeneratePdf page to generate bill in PDF format
 * 
 * Revision History:
 *
 * Version       Date                 Author              Comments
 *  1.0        22/2/2013           Ketaki Virkar        Initial Draft
 *
 */

public with sharing class GeneratePdfController 
{	
	Quote quote = new Quote();
	Purchase_Order__c purchaseOrder;
	List<Quote_Purchase__c> quotePurchaseList = new List<Quote_Purchase__c>();
		
	public GeneratePdfController(ApexPages.StandardController Controller)
	{
		purchaseOrder = [select id, Quote__c, Total_Bill__c, Grand_Total__c
		                 from Purchase_Order__c
		                 where id =: ApexPages.currentPage().getParameters().get('id')
		                ];
		
		quote = [Select q.TotalPrice, q.Tax, q.Subtotal, q.Status, q.ShippingStreet, q.ShippingState,
						q.ShippingPostalCode, q.ShippingName, q.ShippingCountry, q.ShippingCity, q.QuoteToState,
						q.QuoteToPostalCode, q.QuoteToName, q.QuoteToCity, q.QuoteNumber, q.QuoteToStreet,
						q.Pricebook2Id, q.Phone, q.OpportunityId, q.Name, q.Id, q.GrandTotal, q.Fax, q.LineItemCount,
						q.ExpirationDate, q.Email, q.Discount, q.ContactId, q.BillingState, q.BillingPostalCode,
						q.BillingName, q.BillingCountry, q.BillingCity, q.BillingStreet, q.AdditionalState,
						q.AdditionalPostalCode, q.AdditionalName, q.AdditionalStreet, q.AdditionalCity
				 From Quote q
				 where q.Id=: purchaseOrder.Quote__c
				];
				
		quotePurchaseList = [Select q.Total_Price__c, q.Sales_Price__c, q.Quote1__c, q.Quantity__c, q.Product1__c,
		                            q.Order__c , q.Name, q.Id, q.Discount__c
		                     From Quote_Purchase__c q
		                     where q.Order__c =: purchaseOrder.Id AND q.Quote1__c =: quote.Id
		                    ];			    
		
	}
	
	public Purchase_Order__c getPurchaseOrder()
	{
		return purchaseOrder;
	}
	
	public void setQuote(Quote q)
	{
		quote = q;
	}
	
	public Quote getQuote()
	{
		return quote;
	}
/*	
	public void setQuotePurchaseList(List<Quote_Purchase__c> qp)
	{
		quotePurchaseList = qp;
	}
*/	
	public List<Quote_Purchase__c> getQuotePurchaseList()
	{
		return quotePurchaseList;
	}

	public Date getCurrentDate()
	{
		return Date.today();
	}
	
	public String getName()
	{
		Opportunity[] opportunity = [Select o.Name, o.Id
		  							 From Opportunity o
		  							 where o.Id =: quote.OpportunityId
		  							];
		return opportunity[0].Name;
	}

}