gitTestProject/src/objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Quote.OpportunityId</field>
                <operation>equals</operation>
                <valueField>$Source.Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gitTestProject/src/objects/Quote_Purchase__c.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Quote Line Item</relationshipLabel>
        <relationshipName>Quote_Purchase</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product1</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Purchase</relationshipLabel>
        <relationshipName>Quote_Purchase</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote1__c</fullName>
        <label>Quote1</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Purchase Order</relationshipLabel>
        <relationshipName>Quote_Purchase</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Price__c</fullName>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote Purchase</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Quote Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Purchase</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gitTestProject/src/classes/OrderHandler.cls
/* Handler for Order Trigger
 * 
 * Revision History:
 *
 * Version       Date                 Author              Comments
 *  1.0        22/2/2013           Ketaki Virkar        Initial Draft
 *
 */

public with sharing class OrderHandler
{
	public OrderHandler()
	{
	}

	public String name(Id pricebookEntryId)
	{
		PricebookEntry pricebookEntry = [Select p.ProductCode, p.Id
										 From PricebookEntry p
										 where p.Id =: pricebookEntryId
										];
		Product2 p = [Select p.ProductCode, p.Name, p.Id
					  From Product2 p
					  where p.ProductCode =: pricebookEntry.ProductCode
					 ];
		return p.Id;
	}
	
	public void Test(Purchase_Order__c purchaseOrder)
	{
		Quote quote = [Select q.Id From Quote q where q.Id =: purchaseOrder.Quote__c];
		
		QuoteLineItem[] qliList = [Select qi.QuoteId, qi.PricebookEntryId, qi.UnitPrice, qi.Quantity, qi.Discount
								   From QuoteLineItem qi
								   where qi.QuoteId =: quote.Id
								  ];
				
		for(QuoteLineItem qli : qliList)
		{
			Quote_Purchase__c objQuotePurchase = new Quote_Purchase__c();
			String productName = name(qli.PricebookEntryId);
			
			objQuotePurchase.Product1__c = productName;
			objQuotePurchase.Sales_Price__c = qli.UnitPrice;
			objQuotePurchase.Quantity__c = qli.Quantity;
			objQuotePurchase.Discount__c = qli.Discount;
			objQuotePurchase.Order__c = purchaseOrder.Id;
			objQuotePurchase.Quote1__c = quote.ID;
			
			insert objQuotePurchase;
		}
	}
}