gitTestProject/src/objects/Quote_Purchase__c.object
<CustomObject>
    <fields>
        <fullName>Product1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product1</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Purchase</relationshipLabel>
        <relationshipName>Quote_Purchase</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Price__c</fullName>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote Purchase</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Quote Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Purchase</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gitTestProject/src/classes/QuotePurchaseHandler.cls
/* Handler for Quote Purchase Trigger
 * 
 * Revision History:
 *
 * Version       Date                 Author              Comments
 *  1.0        22/1/2012           Ketaki Virkar        Initial Draft
 *
 */

public with sharing class QuotePurchaseHandler
{
	public QuotePurchaseHandler()
	{
	}
	
	public void test(Quote_Purchase__c quotePurchase)
	{
		List<PriceBookEntry> priceBookEntry = [Select p.UnitPrice, p.Product2Id, p.Name, p.Id
											   From PricebookEntry p
											   where p.Product2Id =: quotePurchase.Product1__c
											  ];
		
		for(PriceBookEntry objPriceBookEntry : priceBookEntry)
		{
			quotePurchase.Sales_Price__c = objPriceBookEntry.UnitPrice;
		}
	}
}